### PR TITLE
3.2.3 refactor: account settings page

### PR DESCRIPTION
**Pull request by RaitaroH**
Fixing sidebar; also some minor text needed to be made dimmer. TV Code input field also themed

Instead of #33 
Fix last thing in issue https://github.com/RaitaroH/YouTube-DeepDark/issues/32

### CODE REVIEW

**Comment by RaitaroH** [comment]
@MaximeRF I fixed what I wanted to fix. Check it out and tell me if it breaks something.

**Comment by MaximeRF** [comment]
Cannot test it right now, I'm not home...
Side question: Don't you think that it would be more simple to override YouTube's variables and track when new ones are added? Have you already tried?

**Comment by RaitaroH** [comment]
Regarding the variable thing...
I do that for AniList already. For youtube on the other hand... ooh boy. There are a lot of them, hard to even track all of em. Not to mention, most importantly, the way I theme things is way different from what would end up if I were to simply overwrite their variables. For example, I care a lot about hover effects, having text blue for important information etc etc. Youtube theme just DOESN'T do that. This is why I am annoyed when some dewd is like: `Aaaa, don't utube ready have dark theme? Y bodhar`. Pretty sure I was on point with that one.

**Comment by RaitaroH** [comment]
@MaximeRF Ah god damn it. I added this in the wrong place XD. Oops.

**Comment by MaximeRF** [comment]
@RaitaroH I know that it would not be the same, your theme is better, I was just wondering.

**Pull request closed without merging**
