### PR TITLE
fund raiser: payments

### PR DESCRIPTION
**Pull request by RaitaroH**
@MaximeRF Right now there is the #TeamTrees fund raiser so I took the time to theme the progress and payments. [Take a look.](https://youtu.be/b34al8YmQSA)

### CODE REVIEW

**Comment by MaximeRF** [comment]
Hi @RaitaroH
I'm a little bit late since you've already merged the PR but I have just tested and see some small "issues":

1.  In the payment window we don't see which amount is selected by default.
2. When we click "Other" amount we don't see the currency symbol and the underlying effect is inversed.
3. When we click "CONTINUE" the last window is not themed at all:
donate now

Keep up the great work!

**Comment by RaitaroH** [comment]
Way ahead of you. Update to latest commit.

**Comment by MaximeRF** [comment]
The test I made was using the latest update 🤔.

**Comment by RaitaroH** [comment]
I PRed something in the meantime here  4ff9cce703144714630fe80aee9ee6b2521f0293
Also this fixes 1 and 2: d43c02f

**Comment by RaitaroH** [comment]
1. ~In the payment window we don't see which amount is selected.~ This needed some fixes for the join button.
2. ~When we click "Other" amount we don't see the currency symbol, and when we click in the field the underline effect is inverted.~ [Fixed](https://github.com/RaitaroH/YouTube-DeepDark/commit/d43c02fb6942341195a6d970b1bc65d57dfd333f#diff-6d8994f41afb2eb4b93021b8e671b261R2297) but might cause issues elsewhere.
3. ~When we click "CONTINUE" the last window is not themed at all~ That was fixed as well in this very PR :P

**Comment by MaximeRF** [comment]
Okay, I'll check this but I'm sure it will be fine. Regarding the wrong code I made my test with, it's because I'm not used to use GitHub yet 😅

**Comment by RaitaroH** [comment]
@MaximeRF what you can do is:
+ if the branch still exists (usually the case when I ask you to take a look at a PR): go below the title of the PR and click on the purple thing so... in this case payments.
image

+ if the PR was merge most likely the branch was deleted too... for this go to `Files Changed`
image
then choose `View file`. You will just see the full code with all the diffs applied.
image

**Comment by RaitaroH** [comment]
Btw @MaximeRF if you are interested in animu streaming check out my bash script for it [here](https://github.com/RaitaroH/adl/tree/arguments_function) (latest commit from PR in progress).

**Comment by MaximeRF** [comment]
Thank you very much for the instructions.
Regarding anime streamings, I don't have much time for distraction unfortunately.

**Pull request merged**
