### PR TITLE
Many fixes/improvements backported from previous pull request

### PR DESCRIPTION
**Pull request by MaximeRF**
No idea why you ignored my previous pull request. I'm the dev of Enhancer for YouTube in case you do not recognise me as MaximeRF ;)

### CODE REVIEW

**Comment by RaitaroH** [comment]
I just didn't see it. I will test this a bit.

**Comment by RaitaroH** [comment]
@MaximeRF Added a few things, made some formatting fixes. Please look at it if I somehow removed something you added.

**Comment by MaximeRF** [comment]
@RaitaroH Everything is okay for me. Since you have fixed some formatting issues I have fixed them all in the latest commit.

**Comment by RaitaroH** [comment]
My fault for not setting tab instead of spaces for css files in vim ¯\_(ツ)_/¯

**Pull request merged**
