### PR TITLE
Added Dark theme variation with Dragon Ball Style

### PR DESCRIPTION
**Pull request by raghavpatnecha**

### CODE REVIEW

**Comment by RaitaroH** [comment]
I don't understand why you did this. The styl file supports adding extra color variables. So what is the point of this js file?
```css
if stylus-deepdark-style == "Deep-Dark" {
			--main-color: #00adee;
			--main-background: #111;
			--second-background: #181818;
			--hover-background: #232323;
			--main-text: #eff0f1;
			--dimmer-text: #ccc;
			--shadow: 0 1px 0.5px rgba(0, 0, 0, .3);
}
```

**Comment by raghavpatnecha** [comment]
Ok I will make a css version of the same

**Comment by raghavpatnecha** [comment]
I made a cs version for same but it seems like its not showing the dark
theme.

If you can have a look at it then it would be great:
https://github.com/raghavpatnecha/YouTube-DeepDark/blob/master/YouTube-DeepDark-DragonBall.css

**Comment by raghavpatnecha** [comment]
Can you have  a look at this https://github.com/raghavpatnecha/YouTube-DeepDark/blob/master/YouTube-DeepDark-DragonBall.css

**Comment by RaitaroH** [comment]
So before you read the explanation below I will suggest you this:
1. use the color picking option that IS already available to you. Thank me later. Use the gear icon next to the theme. Get said menu by clicking on the stylus addon. If you don't know what I am saying check the documentation available. Is not hard at all. You can also add the colors inside the code if you want to.
2. create a new theme just for yourself that changes the stuff you want. This way you have a smaller theme overall. I have detailed info below telling you how to achieve what you want.

Oh and forgot to mention most people don't even use CLASSIC anymore and even getting classic requires some cookie editing. With that in mind your code would be usable to you and almost nobody else. For that reason, and the fact your code is not even properly written, nor does it have consistent spacing, and even has multiple `data:image` that make stylus lag... I won't merge even if you get it working.

---

The reason why nothing is showing up is because you haven't used the CSS variables anywhere. You see. Those are not somehow part of the Stylus extension, they are user defined.
```css
a.yt-formatted-string {
	color: var(--main-color) !important;
}
```
So now those links will be blue as defined in deepdark color scheme. What you want is to do this:
1. make a color scheme like the ones I have where you just replace the colors. This will make my code work with your colors. You just need 6 colors. So in reality what you need is just the to add a new line [here](https://github.com/RaitaroH/YouTube-DeepDark/blob/master/YouTubeDeepDarkMaterial.user.css#L40). Then copy paste an if block from [here](https://github.com/RaitaroH/YouTube-DeepDark/blob/9adeeb5424de54c5d9e0599376e7bc07ca94a1ba/YouTubeDeepDarkMaterial.user.css#L300) and add it [here](https://github.com/RaitaroH/YouTube-DeepDark/blob/master/YouTubeDeepDarkMaterial.user.css#L308). Now you can have the Dragonball color scheme available to you in the addon (click on the addon button, then the gear next to the theme).
2. because I noticed you have some elements that are distinct such as a custom logo... use an if statement at the bottom of my code where you put those. Even better make a new `@moz` block and have those there. Look at my duckduckgo theme where I do this or look [here](https://github.com/openstyles/stylus/wiki/Writing-styles). For the if statements either look at my stylus theme or in the documentation as well. I already have the variable used for colors so you can simply use it to trigger the if block like the code below.

```css
@-moz-document domain("youtube.com") {

  if stylus-deepdark-style == "Dragonball-Dark" {
    body > .container {
      padding-top: 0 !important;
    }
    body > footer {
      backgroun-color: var(--background-color) !important;
    }
   /* extra code here bla bla bla */
  }
}
```

**Pull request closed without merging**
