### PR TITLE
Fix account pages

### PR DESCRIPTION
**Pull request by MaximeRF**

### CODE REVIEW

**Comment by RaitaroH** [comment]
I will have to do some refactoring I suppose for this.

**Comment by MaximeRF** [comment]
Why? Everything is fixed for me. Have you experienced another issue?

**Comment by RaitaroH** [comment]
Well the code I had before [here](https://github.com/RaitaroH/YouTube-DeepDark/blob/5ed0cbf32db4b81e9bc3b411bdc060c344975952/YouTubeDeepDarkMaterial.user.css#L560) now needs to be replaced with what you added... AND I also need to add some dimmer-text for different things like email, descriptions bla bla bla.

**Comment by MaximeRF** [comment]
Okay, I understand.
Side question: Don't you think that it would be more simple to override YouTube's variables and track when new ones are added?

**Comment by RaitaroH** [comment]
Wait haven't I responded to this already? Hmmm, maybe I didn't comment idk.

In short:
+ there are too many yt vars
+ they change a lot
+ even if I did I want to change how some things look

So yeah not a bad idea, I already am doing this for AniList but I gave up on youtube. I started at first with it but it turned out better this way. @MaximeRF give it a shot if you want but is kinda messy.

**Pull request closed without merging**
