### PR TITLE
Aditions by MRFDEV

### PR DESCRIPTION
**Pull request by RaitaroH**
@MechaLynx Can you take a look. I have no time at the moment.

### CODE REVIEW

**Comment by RaitaroH** [comment]
In the classic at least it seems he just added the `{` to the next line.

**Comment by RaitaroH** [comment]
@mrfdev I did noticed the variable class changes. Besides that the white spacing removal and the the bracket to the new line. Have you added something else?

**Comment by MechaLynx** [comment]
@RaitaroH Sorry, I can't spare any time either. This is will have to wait.

**Comment by MechaLynx** [comment]
Both files have formatting changes, some of which are correctional (extraneous whitespace), others are a matter of style (personally, I prefer the brackets to be on the same line as the selector but that's just taste, I don't care either way).

The changes on Classic also have modifications to the styles used for the Creator Studio which I'm eager to see but don't have time to review at the moment.

@mrfdev Sorry for the long delay, the last few months have been difficult. Thanks for the patience.

**Comment by RaitaroH** [comment]
Outdated. (classic is also done, so who cares)

**Pull request closed without merging**
